# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kasper/prg/cpp/3D-Asteroids

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kasper/prg/cpp/3D-Asteroids

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kasper/prg/cpp/3D-Asteroids/CMakeFiles /home/kasper/prg/cpp/3D-Asteroids//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kasper/prg/cpp/3D-Asteroids/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Asteroids

# Build rule for target.
Asteroids: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Asteroids
.PHONY : Asteroids

# fast build rule for target.
Asteroids/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/build
.PHONY : Asteroids/fast

src/asteroid.o: src/asteroid.cpp.o
.PHONY : src/asteroid.o

# target to build an object file
src/asteroid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/asteroid.cpp.o
.PHONY : src/asteroid.cpp.o

src/asteroid.i: src/asteroid.cpp.i
.PHONY : src/asteroid.i

# target to preprocess a source file
src/asteroid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/asteroid.cpp.i
.PHONY : src/asteroid.cpp.i

src/asteroid.s: src/asteroid.cpp.s
.PHONY : src/asteroid.s

# target to generate assembly for a file
src/asteroid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/asteroid.cpp.s
.PHONY : src/asteroid.cpp.s

src/convexhull.o: src/convexhull.cpp.o
.PHONY : src/convexhull.o

# target to build an object file
src/convexhull.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/convexhull.cpp.o
.PHONY : src/convexhull.cpp.o

src/convexhull.i: src/convexhull.cpp.i
.PHONY : src/convexhull.i

# target to preprocess a source file
src/convexhull.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/convexhull.cpp.i
.PHONY : src/convexhull.cpp.i

src/convexhull.s: src/convexhull.cpp.s
.PHONY : src/convexhull.s

# target to generate assembly for a file
src/convexhull.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/convexhull.cpp.s
.PHONY : src/convexhull.cpp.s

src/framebuffer.o: src/framebuffer.cpp.o
.PHONY : src/framebuffer.o

# target to build an object file
src/framebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/framebuffer.cpp.o
.PHONY : src/framebuffer.cpp.o

src/framebuffer.i: src/framebuffer.cpp.i
.PHONY : src/framebuffer.i

# target to preprocess a source file
src/framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/framebuffer.cpp.i
.PHONY : src/framebuffer.cpp.i

src/framebuffer.s: src/framebuffer.cpp.s
.PHONY : src/framebuffer.s

# target to generate assembly for a file
src/framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/framebuffer.cpp.s
.PHONY : src/framebuffer.cpp.s

src/loadOBJ.o: src/loadOBJ.cpp.o
.PHONY : src/loadOBJ.o

# target to build an object file
src/loadOBJ.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/loadOBJ.cpp.o
.PHONY : src/loadOBJ.cpp.o

src/loadOBJ.i: src/loadOBJ.cpp.i
.PHONY : src/loadOBJ.i

# target to preprocess a source file
src/loadOBJ.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/loadOBJ.cpp.i
.PHONY : src/loadOBJ.cpp.i

src/loadOBJ.s: src/loadOBJ.cpp.s
.PHONY : src/loadOBJ.s

# target to generate assembly for a file
src/loadOBJ.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/loadOBJ.cpp.s
.PHONY : src/loadOBJ.cpp.s

src/loadshaders.o: src/loadshaders.cpp.o
.PHONY : src/loadshaders.o

# target to build an object file
src/loadshaders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/loadshaders.cpp.o
.PHONY : src/loadshaders.cpp.o

src/loadshaders.i: src/loadshaders.cpp.i
.PHONY : src/loadshaders.i

# target to preprocess a source file
src/loadshaders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/loadshaders.cpp.i
.PHONY : src/loadshaders.cpp.i

src/loadshaders.s: src/loadshaders.cpp.s
.PHONY : src/loadshaders.s

# target to generate assembly for a file
src/loadshaders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/loadshaders.cpp.s
.PHONY : src/loadshaders.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/matrix.o: src/matrix.cpp.o
.PHONY : src/matrix.o

# target to build an object file
src/matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/matrix.cpp.o
.PHONY : src/matrix.cpp.o

src/matrix.i: src/matrix.cpp.i
.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/matrix.cpp.i
.PHONY : src/matrix.cpp.i

src/matrix.s: src/matrix.cpp.s
.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/matrix.cpp.s
.PHONY : src/matrix.cpp.s

src/particles.o: src/particles.cpp.o
.PHONY : src/particles.o

# target to build an object file
src/particles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/particles.cpp.o
.PHONY : src/particles.cpp.o

src/particles.i: src/particles.cpp.i
.PHONY : src/particles.i

# target to preprocess a source file
src/particles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/particles.cpp.i
.PHONY : src/particles.cpp.i

src/particles.s: src/particles.cpp.s
.PHONY : src/particles.s

# target to generate assembly for a file
src/particles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/particles.cpp.s
.PHONY : src/particles.cpp.s

src/player.o: src/player.cpp.o
.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/polygon.o: src/polygon.cpp.o
.PHONY : src/polygon.o

# target to build an object file
src/polygon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/polygon.cpp.o
.PHONY : src/polygon.cpp.o

src/polygon.i: src/polygon.cpp.i
.PHONY : src/polygon.i

# target to preprocess a source file
src/polygon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/polygon.cpp.i
.PHONY : src/polygon.cpp.i

src/polygon.s: src/polygon.cpp.s
.PHONY : src/polygon.s

# target to generate assembly for a file
src/polygon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/polygon.cpp.s
.PHONY : src/polygon.cpp.s

src/random.o: src/random.cpp.o
.PHONY : src/random.o

# target to build an object file
src/random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/random.cpp.o
.PHONY : src/random.cpp.o

src/random.i: src/random.cpp.i
.PHONY : src/random.i

# target to preprocess a source file
src/random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/random.cpp.i
.PHONY : src/random.cpp.i

src/random.s: src/random.cpp.s
.PHONY : src/random.s

# target to generate assembly for a file
src/random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/random.cpp.s
.PHONY : src/random.cpp.s

src/shooter.o: src/shooter.cpp.o
.PHONY : src/shooter.o

# target to build an object file
src/shooter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/shooter.cpp.o
.PHONY : src/shooter.cpp.o

src/shooter.i: src/shooter.cpp.i
.PHONY : src/shooter.i

# target to preprocess a source file
src/shooter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/shooter.cpp.i
.PHONY : src/shooter.cpp.i

src/shooter.s: src/shooter.cpp.s
.PHONY : src/shooter.s

# target to generate assembly for a file
src/shooter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/shooter.cpp.s
.PHONY : src/shooter.cpp.s

src/skybox.o: src/skybox.cpp.o
.PHONY : src/skybox.o

# target to build an object file
src/skybox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/skybox.cpp.o
.PHONY : src/skybox.cpp.o

src/skybox.i: src/skybox.cpp.i
.PHONY : src/skybox.i

# target to preprocess a source file
src/skybox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/skybox.cpp.i
.PHONY : src/skybox.cpp.i

src/skybox.s: src/skybox.cpp.s
.PHONY : src/skybox.s

# target to generate assembly for a file
src/skybox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/skybox.cpp.s
.PHONY : src/skybox.cpp.s

src/vertexarrays.o: src/vertexarrays.cpp.o
.PHONY : src/vertexarrays.o

# target to build an object file
src/vertexarrays.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/vertexarrays.cpp.o
.PHONY : src/vertexarrays.cpp.o

src/vertexarrays.i: src/vertexarrays.cpp.i
.PHONY : src/vertexarrays.i

# target to preprocess a source file
src/vertexarrays.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/vertexarrays.cpp.i
.PHONY : src/vertexarrays.cpp.i

src/vertexarrays.s: src/vertexarrays.cpp.s
.PHONY : src/vertexarrays.s

# target to generate assembly for a file
src/vertexarrays.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Asteroids.dir/build.make CMakeFiles/Asteroids.dir/src/vertexarrays.cpp.s
.PHONY : src/vertexarrays.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Asteroids"
	@echo "... src/asteroid.o"
	@echo "... src/asteroid.i"
	@echo "... src/asteroid.s"
	@echo "... src/convexhull.o"
	@echo "... src/convexhull.i"
	@echo "... src/convexhull.s"
	@echo "... src/framebuffer.o"
	@echo "... src/framebuffer.i"
	@echo "... src/framebuffer.s"
	@echo "... src/loadOBJ.o"
	@echo "... src/loadOBJ.i"
	@echo "... src/loadOBJ.s"
	@echo "... src/loadshaders.o"
	@echo "... src/loadshaders.i"
	@echo "... src/loadshaders.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/particles.o"
	@echo "... src/particles.i"
	@echo "... src/particles.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/polygon.o"
	@echo "... src/polygon.i"
	@echo "... src/polygon.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/shooter.o"
	@echo "... src/shooter.i"
	@echo "... src/shooter.s"
	@echo "... src/skybox.o"
	@echo "... src/skybox.i"
	@echo "... src/skybox.s"
	@echo "... src/vertexarrays.o"
	@echo "... src/vertexarrays.i"
	@echo "... src/vertexarrays.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

