# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kasper/prg/fun/3D-Asteroids

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kasper/prg/fun/3D-Asteroids

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kasper/prg/fun/3D-Asteroids/CMakeFiles /home/kasper/prg/fun/3D-Asteroids/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kasper/prg/fun/3D-Asteroids/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named application

# Build rule for target.
application: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 application
.PHONY : application

# fast build rule for target.
application/fast:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/build
.PHONY : application/fast

# target to build an object file
src/HUD.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/HUD.o
.PHONY : src/HUD.o

# target to preprocess a source file
src/HUD.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/HUD.i
.PHONY : src/HUD.i

# target to generate assembly for a file
src/HUD.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/HUD.s
.PHONY : src/HUD.s

# target to build an object file
src/asteroid.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/asteroid.o
.PHONY : src/asteroid.o

# target to preprocess a source file
src/asteroid.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/asteroid.i
.PHONY : src/asteroid.i

# target to generate assembly for a file
src/asteroid.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/asteroid.s
.PHONY : src/asteroid.s

# target to build an object file
src/convexhull.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/convexhull.o
.PHONY : src/convexhull.o

# target to preprocess a source file
src/convexhull.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/convexhull.i
.PHONY : src/convexhull.i

# target to generate assembly for a file
src/convexhull.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/convexhull.s
.PHONY : src/convexhull.s

# target to build an object file
src/framebuffer.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/framebuffer.o
.PHONY : src/framebuffer.o

# target to preprocess a source file
src/framebuffer.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/framebuffer.i
.PHONY : src/framebuffer.i

# target to generate assembly for a file
src/framebuffer.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/framebuffer.s
.PHONY : src/framebuffer.s

# target to build an object file
src/loadOBJ.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/loadOBJ.o
.PHONY : src/loadOBJ.o

# target to preprocess a source file
src/loadOBJ.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/loadOBJ.i
.PHONY : src/loadOBJ.i

# target to generate assembly for a file
src/loadOBJ.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/loadOBJ.s
.PHONY : src/loadOBJ.s

# target to build an object file
src/loadshaders.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/loadshaders.o
.PHONY : src/loadshaders.o

# target to preprocess a source file
src/loadshaders.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/loadshaders.i
.PHONY : src/loadshaders.i

# target to generate assembly for a file
src/loadshaders.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/loadshaders.s
.PHONY : src/loadshaders.s

# target to build an object file
src/main.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/main.o
.PHONY : src/main.o

# target to preprocess a source file
src/main.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/main.i
.PHONY : src/main.i

# target to generate assembly for a file
src/main.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/main.s
.PHONY : src/main.s

# target to build an object file
src/matrix.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/matrix.o
.PHONY : src/matrix.o

# target to preprocess a source file
src/matrix.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/matrix.i
.PHONY : src/matrix.i

# target to generate assembly for a file
src/matrix.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/matrix.s
.PHONY : src/matrix.s

# target to build an object file
src/particles.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/particles.o
.PHONY : src/particles.o

# target to preprocess a source file
src/particles.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/particles.i
.PHONY : src/particles.i

# target to generate assembly for a file
src/particles.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/particles.s
.PHONY : src/particles.s

# target to build an object file
src/player.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/player.o
.PHONY : src/player.o

# target to preprocess a source file
src/player.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/player.i
.PHONY : src/player.i

# target to generate assembly for a file
src/player.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/player.s
.PHONY : src/player.s

# target to build an object file
src/polygon.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/polygon.o
.PHONY : src/polygon.o

# target to preprocess a source file
src/polygon.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/polygon.i
.PHONY : src/polygon.i

# target to generate assembly for a file
src/polygon.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/polygon.s
.PHONY : src/polygon.s

# target to build an object file
src/random.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/random.o
.PHONY : src/random.o

# target to preprocess a source file
src/random.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/random.i
.PHONY : src/random.i

# target to generate assembly for a file
src/random.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/random.s
.PHONY : src/random.s

# target to build an object file
src/shooter.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/shooter.o
.PHONY : src/shooter.o

# target to preprocess a source file
src/shooter.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/shooter.i
.PHONY : src/shooter.i

# target to generate assembly for a file
src/shooter.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/shooter.s
.PHONY : src/shooter.s

# target to build an object file
src/skybox.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/skybox.o
.PHONY : src/skybox.o

# target to preprocess a source file
src/skybox.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/skybox.i
.PHONY : src/skybox.i

# target to generate assembly for a file
src/skybox.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/skybox.s
.PHONY : src/skybox.s

# target to build an object file
src/vertexarrays.o:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/vertexarrays.o
.PHONY : src/vertexarrays.o

# target to preprocess a source file
src/vertexarrays.i:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/vertexarrays.i
.PHONY : src/vertexarrays.i

# target to generate assembly for a file
src/vertexarrays.s:
	$(MAKE) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/src/vertexarrays.s
.PHONY : src/vertexarrays.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... application"
	@echo "... src/HUD.o"
	@echo "... src/HUD.i"
	@echo "... src/HUD.s"
	@echo "... src/asteroid.o"
	@echo "... src/asteroid.i"
	@echo "... src/asteroid.s"
	@echo "... src/convexhull.o"
	@echo "... src/convexhull.i"
	@echo "... src/convexhull.s"
	@echo "... src/framebuffer.o"
	@echo "... src/framebuffer.i"
	@echo "... src/framebuffer.s"
	@echo "... src/loadOBJ.o"
	@echo "... src/loadOBJ.i"
	@echo "... src/loadOBJ.s"
	@echo "... src/loadshaders.o"
	@echo "... src/loadshaders.i"
	@echo "... src/loadshaders.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/particles.o"
	@echo "... src/particles.i"
	@echo "... src/particles.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/polygon.o"
	@echo "... src/polygon.i"
	@echo "... src/polygon.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/shooter.o"
	@echo "... src/shooter.i"
	@echo "... src/shooter.s"
	@echo "... src/skybox.o"
	@echo "... src/skybox.i"
	@echo "... src/skybox.s"
	@echo "... src/vertexarrays.o"
	@echo "... src/vertexarrays.i"
	@echo "... src/vertexarrays.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

